# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Forum_Client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Forum_Client

pod 'CocoaAsyncSocket'

end
